@testset "Quadratic and hermitian forms" begin
  @showtime include("QuadForm/Basic.jl")
  @showtime include("QuadForm/Lattices.jl")
  @showtime include("QuadForm/Genus.jl")
  @showtime include("QuadForm/Morphism.jl")
  @showtime include("QuadForm/Enumeration.jl")
  @showtime include("QuadForm/ShortVectors.jl")
  @showtime include("QuadForm/MassQuad.jl")
  @showtime include("QuadForm/Quad.jl")
  @showtime include("QuadForm/QuadBin.jl")
  @showtime include("QuadForm/Herm.jl")
  @showtime include("QuadForm/Torsion.jl")
  @showtime include("QuadForm/Quad/PadicLift.jl")
  @showtime include("QuadForm/CloseVectors.jl")
  @showtime include("QuadForm/indefiniteLLL.jl")
  @showtime include("QuadForm/IO.jl")
  @showtime include("QuadForm/Database.jl")
end
