@showtime include("Quad/Lattices.jl")
@showtime include("Quad/Spaces.jl")
@showtime include("Quad/Genus.jl")
@showtime include("Quad/GenusRep.jl")
@showtime include("Quad/ZLattices.jl")
@showtime include("Quad/NormalForm.jl")
@showtime include("Quad/ZGenus.jl")
